### PR TITLE
another 6.1.0 update attempt

### PR DESCRIPTION
**Pull request by loriab**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by loriab** [comment]
DO NOT MERGE!
* haven't rerendered
* turned off 3rd/4th deriv as test to see if that's why Linux is timing out at about 75% around m11_l and beef files

**Comment by loriab** [comment]
@conda-forge-admin, please rerender

**Comment by loriab** [comment]
Thanks for working on the v6 update over at #39, @vanderhe. I encountered the same linux build failures you hit, but I think the tests are ok, as all 19k run in a couple minutes. It looked like the linux builds were timing out after 3h/75% around files x_m11_l and beef. I confirmed that upon turning off 3rd and 4th derivatives the linux-64 builds take <20 min. I'm currently testing turning the 3rd deriv back on; several have finished within an hour. So @jan-janssen @bjodah, how necessary are 4th deriv? (They're already off for Mac, Win, Linux aarch64.) Or @susilehtola, any advice for partial enabling?

**Comment by susilehtola** [comment]
4th derivatives are needed e.g. for TDDFT Hessians, but I do not know if any free or open source code supports them. In Fedora I ship 4th derivatives for all 64-bit architectures. I had to turn fourth derivatives off on 32-bit targets at some point due to build failures related to issues with link time optimization.

**Comment by vanderhe** [comment]
> [...] I think the tests are ok, as all 19k run in a couple minutes.
> I confirmed that upon turning off 3rd and 4th derivatives the linux-64 builds take <20 min.

I adapted `-DDISABLE_LXC=ON` as well as re-activated all regression tests in #39.

**Comment by loriab** [comment]
Continuing at https://gitlab.com/libxc/libxc/-/issues/448 .

**Comment by bjodah** [comment]
A small observation from the peanut gallery:
A short term work-around could be to carry patches in the recipe adding:
```C
#pragma GCC optimize ("O1")
```
at the beginning of the translation units being the worst offenders (the `.c` files taking the longest to compile).

**Comment by loriab** [comment]
good news, the 4th deriv builds with a modest truncation of fctls are finishing in time. red "x"s are because recipe is checking for the f90 lib, which has apparently been dropped from libxc master, which is the base of the branch I pulled from.

**Comment by loriab** [comment]
If the build I just started succeeds, I think it's reasonable to merge.

**Pull request merged**
