### PR TITLE
Enable kxc and lxc

### LINKED ISSUE #26: Enable KXC and LXC
Hi,

I'm currently in the process of adding pyscf to conda-forge which depends on libxc. Here, some of my tests fail due to a missing KXC.

Upstream has informed me that this can be solved by compiling with the option `-DDISABLE_KXC=OFF`, as outlined in this issue: https://github.com/pyscf/pyscf/issues/1103

Are you happy with me opening a PR adding that flag?

Additionally, @susilehtola (Who has commented here before) has suggested that `-DDISABLE_LXC=OFF` gets also added to build the full library. This can take a couple of hours so we will have to check if this can be done by conda-forge.

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #26

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
For the Travis builds: Are you happy with me trying emulation there as the 50 minutes will probably never be enough.

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
Hmm that takes a lot longer. How about skipping the extra options on ppc64?

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
We probably need `test_on_native_only: true` but let's see.

**Comment by BastianZim** [comment]
I copied the approach from one of my feedstocks where it was added by the bot: https://github.com/conda-forge/rectangle-packer-feedstock/blob/master/conda-forge.yml

**Comment by chrisburr** [comment]
> `test_on_native_only`

This only needed for `osx-arm64` and deprecated now in favour of a more flexible option: https://github.com/conda-forge/conda-smithy/releases/tag/v3.14.0

**Comment by BastianZim** [comment]
Ahh, thanks. Is the rest correct? I added a bit more than what you suggested but it was added by the bot to one of my feedstocks.

**Comment by BastianZim** [comment]
So this is outdated then, right? https://conda-forge.org/docs/maintainer/conda_forge_yml.html#test-on-native-only

**Comment by BastianZim** [comment]
@conda-forge-admin, please restart ci

**Comment by chrisburr** [comment]
> Ahh, thanks. Is the rest correct? I added a bit more than what you suggested but it was added by the bot to one of my feedstocks.

Yup, looks good :+1: Though you should probably pass `$CMAKE_ARGS` to `cmake` in the build script (I might have the var name slighly wrong).

> So this is outdated then, right? https://conda-forge.org/docs/maintainer/conda_forge_yml.html#test-on-native-only

Yup 😅

**Comment by BastianZim** [comment]
Was correct, thanks! Let's see if that's also the way to write it on windows...

**Comment by BastianZim** [comment]
@chrisburr 

> This only needed for osx-arm64 and deprecated now in favour of a more flexible option: https://github.com/conda-forge/conda-smithy/releases/tag/v3.14.0

The tests still fail though, I haven't looked at the feedstock enough to determine if that's because of the cross-compilation or something else but I'm leaning towards cross-compilation and would add `test: native_and_emulated`. What do you think?

**Comment by chrisburr** [comment]
The issue is that the `ldd` test isn't going to work for emulation as you're running an `x86_64` executable (`ldd`) and then trying to load `aarch64` shared library (`libxc.so`) into the same process. The emulation only kicks in if you try to launch an `aarch64` executable.

You can avoid the issue by changing the selector to `# [linux and build_platform == target_platform]`.

**Comment by BastianZim** [comment]
Thank you!

**Comment by chrisburr** [comment]
A few clarifications:

* cross-compilation only effects the build process itself and normally just mean you can compile at native speed. The only downside is that the package's build system has to do things the "right" way for it to work.
* emulation doesn't require the package to be correctly set up but it's very slow as you're converting every `aarch64` instruction to a series of `x86_64` instructions. In my (very) limited experience it's ~6x slower. (which is frankly quite impressive!)
* Regardless of if you cross-compile or emulate the build you always have to run the tests with emulation (or skip them entirely like we do on `osx-arm64`). Luckily some wizards have made emulation relatively transparent to use unless you hit an edge case like complex instructions that are unsupported by QEMU or the thing you had with `ldd`. (If you installed `ldd` for `aarch64` it would be fine but it's not worth the hassle of figuring out where we can find it.)

**Comment by BastianZim** [comment]
Ahh ok, to be honest, 95% of my recipes are pure python so this is quite foreign to me but always nice to learn something new. Thanks!

**Comment by BastianZim** [comment]
@conda-forge-admin, please restart ci

Restarting for failed OSX test.

**Comment by BastianZim** [comment]
Trying to restart the test again.

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
Hmm seems like cross-compilation didn't work as intended. If someone knows how to fix that, great! Otherwise, I'd exclude the additional flags there.

**Comment by BastianZim** [comment]
@conda-forge/libxc Seems to be working now, except for some of the tests. Since these only fail on ppc64le and only 16 of them, I'm not sure if this is something in the package that doesn't work with cross-compilation or the architecture. Do you have any experience with this?

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
Travis times out after 50 mins.

**Comment by BastianZim** [comment]
@jan-janssen This doesn't work because the build-platform is set to linux_64. Also, Travis times out after 50 mins which is not enough for this build.

**Comment by jan-janssen** [comment]
Ok, sorry - then maybe we only enable `lxc` and `kxc` for the architectures which support the build process.

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
@jan-janssen This should be good to go.

**Comment by BastianZim** [comment]
Thanks for merging! :)

**Pull request merged**
