### PR TITLE
try multiplatform cmake build

### LINKED ISSUE #2: cmake for linux/mac
Hi, @bjodah, would you care to collaborate on this recipe?

I'm the one who wrote the https://github.com/psi4/psi4meta/tree/master/conda-recipes/libxc . Only reason I've kept that and others on a separate channel is because of the special performance optimization flags for Intel compilers. Thanks for starting this recipe up here at `c-f`.

My reservation is that this recipe uses libtool for the build on Linux & Mac rather than cmake. The cmake build writes out the `.pc` files that libtool detection needs, as well as its own `LibxcConfig.cmake` for cmake detection. But the libtool build can only write out its own files. The package for which I packaged up libxc, psi4, needs the cmake Config files, so if someone accidentally tried to build psi against this c-f conda package, they would get an error. The Libxc people know about my conda package, so I doubt they'd be against this one using cmake (unless you've heard to the contrary).

I was also thinking that the `run_exports` could be generalized from `x.x` to `x`, since I know from experience how committed they are to preserving semantic versioning contracts.

### PR DESCRIPTION
**Pull request by loriab**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] ~Bumped the build number (if the version is unchanged)~
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Hi, this is a very slow follow-up to #2. Hope I'm not imposing. I'm trying to:
- [x] convert the Linux build to cmake for consistency and because there's [some talk](https://gitlab.com/libxc/libxc/-/issues/225#note_437053464) of consolidating there
- [x] get mac build going
- [x] get windows build going
- [ ] separate `libxc-fortran`

Please feel free to ignore this PR for now (unless you've objections to it) while I play around with the build.

closes #2

### CODE REVIEW

**Comment by loriab** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@loriab Great work - thanks a lot

**Comment by loriab** [comment]
> Great work - thanks a lot

Thanks!

I've got it largely working, but there's a few more things to do:

- [ ] I wonder if the plain C library and the Fortran libraries should be separate packages (latter depending on former). My main concern is that there's a GNU openmp dependency I think brought in by Fortran. Not only is it unneeded since there's no threading in Libxc, having gomp instead of omp/iomp5 is going to break psi4 if this libxc is installed instead of the one from the psi4 channel.
- [ ] the built packages on Azure don't seem to be uploading as artifacts, so I'm unable to download them and test them downstream. For the Windows, I may fake try to build them on staged recipes so as to download and test them. 
- [ ] can't merge, of course, until v5.1 is minted upstream, so needed changes are in and can get a stable sha256

**Comment by loriab** [comment]
@conda-forge-admin, please rerender

**Comment by ltalirz** [comment]
thanks, looking forward to this for the cp2k feedstock as well!

**Comment by loriab** [comment]
In my view, this is ready-to-go pending the v5.1 release.

**Comment by loriab** [comment]
I think this is ready for consideration, @jan-janssen

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Review by jan-janssen — APPROVED** [review]
Looks good to me - thanks a lot

**Comment by ltalirz** [comment]
@loriab given that many codes haven't yet moved to libxc 5, I think it would be quite useful to have a multi-platform build of libxc4 as well. Would it be straightforward to release a multiplatform build of libxc 4 as well or has the build process changed a lot?

**Pull request merged**
