### PR TITLE
Upgrade to libXC version 6.0.0

### PR DESCRIPTION
**Pull request by vanderhe**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by vanderhe** [comment]
@conda-forge-admin, please rerender

**Comment by vanderhe** [comment]
@conda-forge-admin, please rerender

**Comment by vanderhe** [comment]
Dear maintainers (@bjodah @jan-janssen @loriab), since we need libXC >=v6.0.0 on conda-forge for one of our projects, this is an attempt to perform the upgrade manually (the bot failed due to changes in the installation directory I suppose). I have also significantly reduced the number of regression tests to shorten the workflow runtimes (a regular execution of all tests is already ensured at other places). If this is not desired, I can of course undo the change. Currently the CI backend seems to have some problems and I am not sure if the failing runs are due to an erroneous recipe or backend.

**Comment by vanderhe** [comment]
@conda-forge-admin, please rerender

**Comment by vanderhe** [comment]
@conda-forge/core Dear core-team, the problems with failing checks that this PR experiences since a while do not seem to resolve themselves simply by re-running jobs. Is there anything that I can do to avoid the "##[error]An error occurred while provisioning resources (Error Type: Disconnect)." message/error? Many thanks in advance.

**Comment by loriab** [comment]
Thanks for keeping this PR up-to-date. But I think since #40 was merged, this is now redundant and should be closed, right?

**Comment by vanderhe** [comment]
Hi @loriab, the reason for me to start working on 6.0.0 (and not 6.1.0) in the first place was that our code is extensively tested using 6.0.0 and I'm still working on getting test coverage to a more reliable percentage. Since #40 has been merged already I guess for this repo there is no point in merging 6.0.0 as well and would be fine with closing this one.

**Comment by jan-janssen** [comment]
> Since #40 has been merged already I guess for this repo there is no point in merging 6.0.0 as well and would be fine with closing this one.

We could also create a separate branch for 6.0.0 if that would help your package.

**Comment by vanderhe** [comment]
> We could also create a separate branch for 6.0.0 if that would help your package.

Thanks; let me close this PR and check some things on our side for v6.1.0. If it turns out that for whatever reason v6.0.0 is required I will reach out to you again.

**Pull request closed without merging**
